### PR TITLE
Rename fishtown-analytics to dbt-labs

### PR DESCRIPTION
**Pull request by stujo**
Suggestion on support for rename of fishtown-analytics to dbt-labs

### CODE REVIEW

**Comment by stujo** [comment]
I don't have a way to test this, so please, before merging, give it a once over test run

**Comment by stujo** [comment]
https://blog.getdbt.com/of-the-community-by-the-community-for-the-community/

**Comment by rbjerrum** [comment]
Thanks @stujo. LGTM - will test in combination with #15 before merging.

**Comment by stujo** [comment]
Thanks! @rbjerrum

**Pull request merged**
